name: aislackbot
channels:
  - defaults
dependencies:
  - python=3.8.3
  - pip
  - pip:
    - google-cloud-bigquery
    - google-api-python-client
    - slackeventsapi
    - python-dotenv
    - oauth2client
    - slackclient
    - slack-bolt
    - catboost
    - gunicorn
    - sklearn
    - gspread
    - xgboost=1.4.2
    - pyarrow
    - pandas
    - nltk
  - brew:
    - libomp  